### PR TITLE
IDF v4.4 support

### PR DESCRIPTION
**Pull request by ilutchenko**
In ESP-IDF v4.4 added a new I2C API without dynamic memory allocation.
I faced some problems while intensively using crypto chip with old API.

Until v4.4 is not in stable branch, new I2C API can be used in
esp-cryptoauthlib with version #ifdef.

### CODE REVIEW

**Review by AdityaHPatwardhan — APPROVED** [review]

**Comment by AdityaHPatwardhan** [comment]
Hi @ilutchenko , Thank you for your contribution in improving esp-cryptoauthlib, The PR looks good to me. I have raised the MR to merge it into the internal code-base. Once that is merged it should be available on GitHub in a couple of days.
Thanks, Aditya

**Comment by mahavirj** [comment]
@ilutchenko 

> In ESP-IDF v4.4 added a new I2C API without dynamic memory allocation.
I faced some problems while intensively using crypto chip with old API.

Could you please elaborate on problems you faced with existing I2C HAL? Any reproducible use-case or application that you can share here?

**Comment by ilutchenko** [comment]
@mahavirj 
Our device is based on ESP32-WROVER-E with 8Mb of external memory.
We develop a complex solution and now we have a big number of FreeRTOS tasks. 
This means that we have not a lot of free memory in internal RAM:
image
Cryptochip and another IC connected to one I2C bus. We frequently write data to the IC, and when we access the cryptochip, we catch such kind of errors:
image
image

**Comment by ilutchenko** [comment]
@mahavirj 
When I prepared answer below, I've found strange thing in I2C driver:

> i2c_cmd_handle_t i2c_cmd_link_create(void)
> {
> #if !CONFIG_SPIRAM_USE_MALLOC
>     i2c_cmd_desc_t *cmd_desc = (i2c_cmd_desc_t *) calloc(1, sizeof(i2c_cmd_desc_t));
> #else
>     i2c_cmd_desc_t *cmd_desc = (i2c_cmd_desc_t *) heap_caps_calloc(1, sizeof(i2c_cmd_desc_t), MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT);
> #endif
>     return (i2c_cmd_handle_t) cmd_desc;
> }

In both situations, when you mapped an external ram to address space or not, this function will allocate memory from internal.
Looks like there is a wrong `#if !CONFIG_SPIRAM_USE_MALLOC` that must be `#if CONFIG_SPIRAM_USE_MALLOC`, (without `!`).
Can you confirm this guess?

**Comment by mahavirj** [comment]
@ilutchenko 

>  Looks like there is a wrong #if !CONFIG_SPIRAM_USE_MALLOC that must be #if CONFIG_SPIRAM_USE_MALLOC, (without !).

I2C driver also supports flag `ESP_INTR_FLAG_IRAM`, which allows for I2C operations to continue whilst flash cache is disabled (no SPIRAM access). To support this, all allocations for data from I2C ISR handler etc. must happen in internal RAM and not in SPIRAM. Hence the current mechanism is correct, which will ensure that allocations are happening from internal memory only. More on this at: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/spi_flash_concurrency.html#iram-safe-interrupt-handlers

However, this could have been little optimized to detect if I2C driver is indeed installed with `ESP_INTR_FLAG_IRAM`, but given signature of this API, it does not very feasible.

>  This means that we have not a lot of free memory in internal RAM:

Coming back to your original problem, I doubt if current solution will really fix the problem here. If internal memory is running really low, then there is chance that some of the other system services (e.g. network operation) might fail as well. Do you suspect some memory leak in I2C HAL?

On side-note, you may find "RAM optimization" guide at https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/performance/ram-usage.html useful in this context.

**Comment by ilutchenko** [comment]
@mahavirj 

> I doubt if current solution will really fix the problem here

At least, when using the new I2C API, memory for buffers allocates from tasks stack, that more predictable than allocating from the heap.
And yes, the errors have gone.

> Do you suspect some memory leak in I2C HAL?
No, but it's very strange why heap allocator failed to allocate memory for I2C transactions while there are still tens of kilobytes of free RAM. Unfortunately,I didn't dig deep into it.

> On side-note, you may find "RAM optimization" guide

Yeah, thanks for the advice. Stack sizes for tasks were given with a huge margin, we will optimize them soon.

**Comment by mahavirj** [comment]
Closing as we were not able to recreate this issue on our side.

**Pull request closed without merging**
